---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-example
  name: grpc-example
  namespace: demo2
spec:
  clusterIP: None
  selector:
    service: grpc-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-example
  namespace: demo2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: grpc-example
    spec:
      containers:
      - name: grpc-py
        image: placeexchange/grpc-demo:latest
        imagePullPolicy: Always
        ports:
        - name: grpc-api
          containerPort: 50051
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grpc-mapping
  namespace: demo2
spec:
  headers:
    :authority: grpc.subdomain2.example.com
  grpc: True
  prefix: /helloworld.Greeter/
  rewrite: /helloworld.Greeter/
  service: grpc-example:50051
---
#Configure host cert
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
  name: grpc
  namespace: demo2
spec:
  acmeProvider:
    email: registration@example.com
  hostname: grpc.subdomain2.example.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: grpc-context
  namespace: demo2
spec:
  hosts:
  - grpc.subdomain2.example.com
  secret: grpc.subdomain2.example.com
  alpn_protocols: h2
