---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: demo
spec:
  clusterIP: None
  selector:
    app: quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: backend
        image: datawire/quote:0.2.7
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote-backend
  namespace: demo
spec:
  host: grpc.subdomain.example.com
  prefix: /quote/
  service: personal:8080
---
#Configure host cert
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
  name: grpc
  namespace: demo
spec:
  acmeProvider:
    email: registration@example.com
  hostname: grpc.subdomain.example.com
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: grpc-context
  namespace: demo
spec:
  hosts:
  - grpc.subdomain.example.com
  secret: grpc.subdomain.example.com
  alpn_protocols: h2
